🌱 NEW: adopted  `hatch-pip-compile` which makes requirements lock files 💎 REFACTOR: `.Style.autopick_fg()` now accounts contrast ratio 💎 REFACTOR: `.IRenderable.splitlines()` is shared now
📙 DOCS: color cube approximation examples
📙 DOCS: `autopick_fg.py` example

diff --git a/run-cli b/run-cli
--- a/run-cli
+++ b/run-cli
@@ -49,7 +49,7 @@ init-venv() {
             return 1
         fi
     fi
-    venv-demo/bin/python -m pip install -r requirements-demo.txt || echo "[ERROR] Failed to install requirements"
+    venv-demo/bin/python -m pip install -r requirements/requirements-demo.txt || echo "[ERROR] Failed to install requirements"
 }
 
 main "$@"
